### ISSUE TITLE
Many Stark tests failing

### ISSUE THREAD

**Issue by Sean4572435243** [0xPolygonHermez/pil-stark#27]
For example: "test fibonacci" output ends with:

```
1) test fibonacci sm
       It should create the pols main:
     RangeError: Array buffer allocation failed
      at new ArrayBuffer (<anonymous>)
      at new BigUint64Array (<anonymous>)
      at new BigBuffer (node_modules\pilcom\src\bigbuffer.js:11:36)
      at starkGen (src\stark_gen.js:74:20)
      at async Context.<anonymous> (test\stark_fibonacci.test.js:51:22)

node_modules/mocha/lib/reporters/base.js:305
Process exited with code 1
```

Running x64 node v16.17.0, Windows 11, lots of RAM, nothing else running.  "test plookup" executes correctly

**Comment by eigmax** [comment]
did you run the code from the master branch?

**Comment by Sean4572435243** [comment]
I did.  I cloned the entire 'main' branch.  I am using Visual Studio Code to work with it.  Most tests work fine, it's just many of the Stark-specific tests exhibit this 'Array buffer allocation failed' error.

**Comment by eigmax** [comment]
try to setup NODE_OPTIONS --max-old-space-size to allow the node to use more memory.

**Comment by Sean4572435243** [comment]
Here's all the output when running the Fibonnaci test.  You can see it initializes node with --max-old-space-size=32000, but it still has the range error at the end.  I don't think this setting is the issue.

```
C:\Program Files\nodejs\node.exe --max-old-space-size=32000 .\node_modules\mocha\bin\_mocha C:\Dev\NewDev\ThirdParty\PIL-STARK/test/stark_fibonacci.test.js

  test fibonacci sm
Result: 74469561660084004
preparing public 1/3
calculateExpression: 0
preparing public 2/3
preparing public 3/3
Checking identities 1/5
calculateExpression: 1
Checking identities 2/5
calculateExpression: 3
calculateExpression: 2
Checking identities 3/5
calculateExpression: 4
Checking identities 4/5
calculateExpression: 5
Checking identities 5/5
calculateExpression: 6
Interpolating reverse....
Layer ifft0
start block 10 0
end block 10 0
Interpolating prepare....
linear interpolatePrepare start.... 0/0
linear interpolatePrepare end.... 0/0
Bit reverse....
Layer fft 0
start block 11 0
end block 11 0
interpolation terminated
pool terminated
slicing buff 0
creating thread 0
waiting..
linear hash start.... 0/2048
merkelizing hash start.... 0/1024
merkelizing hash end.... 0/1024
merkelizing hash start.... 0/512
merkelizing hash end.... 0/512
merkelizing hash start.... 0/256
merkelizing hash end.... 0/256
merkelizing hash start.... 0/128
merkelizing hash end.... 0/128
merkelizing hash start.... 0/64
merkelizing hash end.... 0/64
merkelizing hash start.... 0/32
merkelizing hash end.... 0/32
merkelizing hash start.... 0/16
merkelizing hash end.... 0/16
merkelizing hash start.... 0/8
merkelizing hash end.... 0/8
merkelizing hash start.... 0/4
merkelizing hash end.... 0/4
merkelizing hash start.... 0/2
merkelizing hash end.... 0/2
merkelizing hash start.... 0/1
merkelizing hash end.... 0/1
maxDeg: 3, nIm: 0, d: 3
27
27
27
27
27
27
    1) It should create the pols main
  0 passing (8s)
  1 failing
  1) test fibonacci sm
       It should create the pols main:
     RangeError: Array buffer allocation failed
      at new ArrayBuffer (<anonymous>)
      at new BigUint64Array (<anonymous>)
      at new BigBuffer (node_modules\pilcom\src\bigbuffer.js:11:36)
      at starkGen (src\stark_gen.js:74:20)
      at async Context.<anonymous> (test\stark_fibonacci.test.js:51:22)
Process exited with code 1

```

**Comment by eigmax** [comment]
check out the error, `at new BigBuffer (node_modules\pilcom\src\bigbuffer.js:11:36)`, 

`        this.buffers[nBuffers-1] = new BigUint64Array(length - MAX_BUFF_SIZE * (nBuffers -1));
`
Can you print out the `length - MAX_BUFF_SIZE * (nBuffers -1)`? to make sure it's not negtive.

**Comment by Sean4572435243** [comment]
In stark_gen.js on lines 72 and 73

```
ctx.cm2_n = new BigBuffer(starkInfo.mapSectionsN.cm2_n*ctx.N);
ctx.cm3_n = new BigBuffer(starkInfo.mapSectionsN.cm3_n*ctx.N);
```

Both cm2_n and cm3_n are zero.  Weirdly enough, the first line's BigBuffer call completes without error, but the second BigBuffer call blows up on line 11 of bigbuffer.js:

`this.buffers[nBuffers-1] = new BigUint64Array(length - MAX_BUFF_SIZE * (nBuffers -1));`

length = 0, and nBuffers = 0, resulting in the ultimate right-side parameter value of MAX_BUFF_SIZE, but with a left-side array reference of -1.  Again, this didn't seem to blow up the first time, but but the second time it does.

**Comment by eigmax** [comment]
cm2_n and cm3_n could be 0 if there are no lookup and permutation checks in the PIL.  I guess the only difference is the node version, we use node 18.

**Comment by Sean4572435243** [comment]
Had my fingers crossed, but updating to node v18.12.1 produced the same error.

**Comment by Sean4572435243** [comment]
On line 11 in bigbuffer.js

        this.buffers[nBuffers-1] = new BigUint64Array(length - MAX_BUFF_SIZE * (nBuffers -1));

When length = 0, and nBuffers = 0, then a new BigUint64Array(MAX_BUFF_SIZE) is created each time, which is a gigabyte in size.  Does this seem correct?  Might be a memory leak.

**Comment by eigmax** [comment]
@Sean4572435243 Can you plz fix the code per PR https://github.com/0xPolygonHermez/pilcom/pull/19/files to check if it works?

**Comment by Sean4572435243** [comment]
That was the fix, thank you! :)
